AWSTemplateFormatVersion: '2010-09-09'
Description: Creating an AutoScaling group with adding LoadBalancing
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: "mykeypair"
  ImageId:
    Type: String
    Description: 'Choose an Amazon Machine Image'
    Default: 'ami-0e6329e222e662a52'
  
  LaunchTemplateVersionNumber:
    Type: String
    Default: 1
  VpcId:
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    Type: 'AWS::EC2::VPC::Id'
    Default: vpc-037fc7e3f7ddaf8d5
  SubnetA:
    Description: Choose a subnets for your VPC
    Type: String
    Default: 'subnet-0841f5252c08625b8'
  SubnetB:
    Description: Choose a subnets for your VPC
    Type: String
    Default: 'subnet-00ad391f60f1ef977'

Resources:
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-launch-template-for-auto-scaling'
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            Groups:
              - !Ref InstanceSecurityGroup
            DeleteOnTermination: true
        Placement:
          Tenancy: default
        ImageId: !Ref ImageId
        KeyName: !Ref KeyName
        InstanceType: t2.micro
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
              systemctl start httpd.service
              systemctl enable httpd.service
              echo “Hello World ....... > /var/www/html/index.html
 

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SG to allow SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Autoscaling group
      Cooldown: 120
      DesiredCapacity: 2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MaxSize: 2
      MinSize: 2
      TargetGroupARNs:
        - Ref: TargetGroup
      VPCZoneIdentifier: 
        - !Ref SubnetA 
        - !Ref SubnetB
        

  ALBListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref TargetGroup
        LoadBalancerArn: !Ref ApplicationLoadBalancer
        Port: 80
        Protocol: HTTP
  ApplicationLoadBalancer:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Scheme: internet-facing 
        Subnets:
          - !Ref SubnetA
          - !Ref SubnetB
        SecurityGroups:
          - !Ref InstanceSecurityGroup
    
  TargetGroup:                                                                                                                                                                              
    Type: AWS::ElasticLoadBalancingV2::TargetGroup                                                                                                                                        
    Properties:
      HealthCheckEnabled: true                                                                                                                                                                           
      VpcId: !Ref VpcId                                                                                                                                                   
      TargetType: instance                                                                                                                                                                
      Port: 80                                                                                                                                                                         
      Protocol: HTTP     
